"use strict";
exports.__esModule = true;
exports.routes = void 0;
var express_1 = require("express");
var trades_routes_1 = require("./trades.routes");
var users_routes_1 = require("./users.routes");
var routes = (0, express_1.Router)();
exports.routes = routes;
routes.use("/users", users_routes_1.userRoutes);
routes.use("/trades", trades_routes_1.tradeRoutes);
