"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRoutes = void 0;
const express_1 = require("express");
const AuthenticateUserController_1 = require("../modules/users/useCases/usersControllers/AuthenticateUserController");
const CreateUserController_1 = require("../modules/users/useCases/usersControllers/CreateUserController");
const userRoutes = (0, express_1.Router)();
exports.userRoutes = userRoutes;
const createUser = new CreateUserController_1.CreateUserController();
const authenticateUser = new AuthenticateUserController_1.AuthenticateUserController();
userRoutes.post("/", createUser.handle);
userRoutes.post("/session", authenticateUser.handle);
